spring.application.name=eventbooking

# Đổi port thành 80
server.port=8080

# Profile mặc định khi chạy local
spring.profiles.active=dev

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Tránh warning + tối ưu JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
